version: "3.2"

services:
  adminer:
    container_name: adminer
    build:
      context: ${HUNCHO_DIR}/services/adminer
      dockerfile: ${HUNCHO_DIR}/services/adminer/build/Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-net
  auth:
    container_name: auth
    build:
      context: ${HUNCHO_DIR}/services/auth
      dockerfile: ${HUNCHO_DIR}/services/auth/build/Dockerfile.qaw
    restart: on-failure
    volumes:
      - ${HUNCHO_DIR}/services/auth/migrations:/home/app/migrations
      - ${HUNCHO_DIR}/services/auth/bin:/home/app/bin
      - ${HUNCHO_DIR}/services/auth/tests:/home/app/tests
      - ${HUNCHO_DIR}/services/auth/src:/home/app/src
      - ${HUNCHO_DIR}/services/auth/statics:/home/app/statics
      - ${HUNCHO_DIR}/services/auth/manage.py:/home/app/manage.py
      - ${HUNCHO_DIR}/services/auth/setup.py:/home/app/setup.py
    env_file:
      - ${HUNCHO_DIR}/env/qaw/.env.auth
    healthcheck:
      test: curl --fail -s auth:5000/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
#      - auth_cache
      - auth_db
    networks:
      - app-net
#  auth_cache:
#    container_name: auth_cache
#    build:
#      context: ${HUNCHO_DIR}/services/redis
#      dockerfile: ${HUNCHO_DIR}/services/redis/build/Dockerfile
#    restart: unless-stopped
#    volumes:
#      - ${HUNCHO_DIR}/data/qaw/auth_cache/redis_data:/var/lib/redis
#      - ${HUNCHO_DIR}/data/qaw/auth_cache/redis.conf:/usr/local/etc/redis/redis.conf
#    env_file:
#      - ${HUNCHO_DIR}/env/qaw/.env.auth_cache
#    healthcheck:
#      test: ["CMD", "redis-cli","ping"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
  auth_db:
    container_name: auth_db
    image: postgres:9.6
    volumes:
      - ${HUNCHO_DIR}/data/qaw/auth_db/data:/var/lib/postgresql/data/
    env_file:
      - ${HUNCHO_DIR}/env/qaw/.env.auth_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - app-net
networks:
  app-net:
    driver: bridge