"""empty message

Revision ID: 10a553c82f4c
Revises: a2ed444a946b
Create Date: 2020-06-22 02:24:18.743612

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10a553c82f4c'
down_revision = 'a2ed444a946b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('user', 'status_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('user', 'role_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
