"""empty message

Revision ID: a2ed444a946b
Revises: 362d9fb651f0
Create Date: 2020-06-22 00:24:52.235363

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a2ed444a946b'
down_revision = '362d9fb651f0'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sqlalchemy_utils.types.password.PasswordType(max_length=1137), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
