"""empty message

Revision ID: 948c682d53fa
Revises: a184d7dae5da
Create Date: 2020-08-22 18:41:27.350874

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '948c682d53fa'
down_revision = 'a184d7dae5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'token', ['uuid'])
    op.create_unique_constraint(None, 'token_status', ['name'])
    op.create_unique_constraint(None, 'user_role', ['name'])
    op.create_unique_constraint(None, 'user_status', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_status', type_='unique')
    op.drop_constraint(None, 'user_role', type_='unique')
    op.drop_constraint(None, 'token_status', type_='unique')
    op.drop_constraint(None, 'token', type_='unique')
    # ### end Alembic commands ###
